# Generated by Django 3.0.7 on 2020-08-03 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0022_auto_20200713_0823'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-date_of_created']},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-date_of_publication']},
        ),
    ]
