# Generated by Django 3.0.7 on 2020-08-04 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0023_auto_20200803_1615'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['date_of_created']},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['date_of_publication']},
        ),
    ]
