# Generated by Django 3.0.7 on 2020-06-17 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
        ('accounts', '0001_initial'),
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='description_of_group',
            field=models.TextField(blank=True, default='This Group has not their destription yet'),
        ),
        migrations.AlterField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='members', related_query_name='member', to='accounts.User'),
        ),
        migrations.AlterField(
            model_name='group',
            name='posts_in_group',
            field=models.ManyToManyField(blank=True, to='posts.Post'),
        ),
    ]
